#!/bin/sh
set -eu
cd "$(dirname "$0")"
if [ ! -e logo.png ]; then
	mv mantis_logo.png logo.png
fi
hsh="$(sha224sum logo.png | awk '{print $1}').png"
ln -sf logo.png "$hsh" 
ln -sf "$hsh" mantis_logo.png 
